# Generated by Django 3.1.6 on 2021-02-04 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField()),
                ('date_receita', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('foto_postagem', models.FileField(blank=True, upload_to='fotos/%m/%Y/')),
            ],
        ),
    ]
