# Generated by Django 3.1.6 on 2021-02-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
