# Generated by Django 3.1.6 on 2021-02-05 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0003_auto_20210205_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='date_receita',
        ),
        migrations.AddField(
            model_name='postagem',
            name='data_postagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data da Postagem'),
        ),
    ]
